### ISSUE TITLE
repo vagueness 

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks-IT/ci-examples#4]
it’s not that we dislike ci-examples @tthyer.  it’s probably just that the doc for it is not clear.  looking at it a little closer now it looks like it’s examples specifically for setting up CI with GH actions to deploy docker containers?

i mean just changing the repo name to be more specific would help

**Comment by tthyer** [comment]
Hi @zaro0508, the purpose of this repository is to provide examples for doing CI, thus the name"ci-examples". These are very simple examples for users just getting started. This has grown out of discussions in the Code Review meeting. This repo is meant to have more examples added to it. Does that make it more clear?

Further, the description clearly states this: "This repository exists to illustrate some CI examples as simply as possible. See .github/worklows folder for the CI workflows."

If more CI examples were added for Travis, the description would change slightly to indicate that there were other examples.
